# This is a basic workflow to help you get started with Actions

name: namt

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
    # Install Ubuntu OS updates
    #- name: Install OS updates, security fixes etc
    #  run: |
        #echo "Installing OS updates, security fixes etc"
        #sudo apt update
        #sudo apt -y upgrade
        #sudo apt -y autoremove
    
    # Install dependancies and Nim language
    - name: Install dependencies and Nim language
      run: |
        echo "Installing Nim language and dependencies..."
        sudo apt -y install build-essential openssl git curl
        curl https://raw.githubusercontent.com/wiremoons/nim-misc/master/nim-install.sh -o nim-install.sh
        chmod 755 ./nim-install.sh
        ./nim-install.sh
        echo "Installed version of Nim and Nimble are:"
        $HOME/.nimble/nim/bin/nim --version
        $HOME/.nimble/bin/nimble --version

    # Install latest Nimble version
    #- name: Install dependencies and Nim language
    #  run: |
      #  echo "Update nimble to current version..."
        #nimble refresh -y
        #nimble install -y nimble
        #nimble version
        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    # Runs a set of commands using the runners shell - include env secret key
    - name: Run a multi-line script
      run: |
        echo "Building the project..."
        pwd
        ls
        PATH="${PATH}":$HOME/.nimble/nim/bin:$HOME/.nimble/bin
        $HOME/.nimble/bin/nimble release
        cd bin/
        ./namt
        ./namt -v
        echo "DONE."

    # Saves built file as a release.
    #- name: Upload artifact
    #  uses: actions/upload-artifact@main
    #  with:
    #    name: release
    #    path: bin